# Use Node.js as the base image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Build Next.js application
RUN npm run build

EXPOSE 3000
CMD ["npm", "run", "start"]
