services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: website_builder
      MYSQL_ROOT_PASSWORD: 
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    container_name: laravel-backend
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: website_builder
      DB_USERNAME: root
      DB_PASSWORD: 
    volumes:
      - ./backend:/var/www
    depends_on:
      - mysql
    ports:
      - '8000:8000'
    command: php artisan serve --host=0.0.0.0 --port=8000
    entrypoint: ["./docker-entrypoint.sh"]

  frontend:
    build:
      context: ./frontend
    container_name: nextjs-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000/api
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    ports:
      - '3000:3000'
    command: npm run dev

volumes:
  mysql-data:
